export const SESSION_COOKIE = 'auth_session';
export const PASSWORD_SALT_ROUNDS = 10;

export const UIStates = {
  SUBSCRIPTION: 'SUBSCRIPTION',
  BIDING_OFFER: 'BIDING_OFFER',

  REGISTER: 'REGISTER',
  REQUEST: 'REQUEST',
  BANKS: 'BANKS',
  STATES: 'STATES',
  COUNTRIES: 'COUNTRIES',
  USER_NOTIFICATION: 'USER_NOTIFICATION',

  LOADING: 'LOADING',

  // MODAL
  REQUEST_HELP_PROVIDER_MODAL: 'REQUEST_HELP_PROVIDER_MODAL',
  ACCEPT_OFFER_MODAL: 'ACCEPT_OFFER_MODAL',
  VIEW_OFFER_MODAL: 'VIEW_OFFER_MODAL',
  NOTIFICATION_DRAWER: 'NOTIFICATION_DRAWER',
  DASHBOARD_NOTIFICATION_DRAWER: 'DASHBOARD_NOTIFICATION_DRAWER',
};
